name: Issue assignment

on:
    issues:
        types: [opened]

permissions:
  contents: read

jobs:
    auto-assign:
        permissions:
          issues: write  # for pozil/auto-assign-issue to assign issues
        runs-on: cx-public-ubuntu-x64
        steps:
            - name: 'Auto-assign issue'
              uses: step-security/auto-assign-issue@4e50a76dff47bf167e113f0428405ae16a41b7c5 # v2.2.2
              with:
                  assignees: phantsure,tiwarishub,anuragc617,vsvipul,bishal-pdmsft
                  numOfAssignee: 1
