name: Validate Data

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate-data:
    permissions:
      contents: read
    runs-on: cx-public-ubuntu-x64
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "12"

      - name: Validate workflows
        run: |
          npm ci
          npx ts-node-script ./index.ts
        working-directory: ./script/validate-data
